// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpcpb/services.proto

package rpcpb

import (
	clientpb "github.com/cryptdefender3232/phantom/protobuf/clientpb"
	commonpb "github.com/cryptdefender3232/phantom/protobuf/commonpb"
	phantompb "github.com/cryptdefender3232/phantom/protobuf/phantompb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpcpb_services_proto protoreflect.FileDescriptor

const file_rpcpb_services_proto_rawDesc = "" +
	"\n" +
	"\x14rpcpb/services.proto\x12\x05rpcpb\x1a\x15commonpb/common.proto\x1a\x17phantompb/phantom.proto\x1a\x15clientpb/client.proto2\xd2d\n" +
	"\n" +
	"PhantomRPC\x120\n" +
	"\n" +
	"GetVersion\x12\x0f.commonpb.Empty\x1a\x11.clientpb.Version\x127\n" +
	"\tClientLog\x12\x17.clientpb.ClientLogData\x1a\x0f.commonpb.Empty(\x01\x124\n" +
	"\fGetOperators\x12\x0f.commonpb.Empty\x1a\x13.clientpb.Operators\x12+\n" +
	"\x04Kill\x12\x12.phantompb.KillReq\x1a\x0f.commonpb.Empty\x12@\n" +
	"\vReconfigure\x12\x19.phantompb.ReconfigureReq\x1a\x16.phantompb.Reconfigure\x12.\n" +
	"\x06Rename\x12\x13.clientpb.RenameReq\x1a\x0f.commonpb.Empty\x122\n" +
	"\vGetSessions\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Sessions\x123\n" +
	"\fMonitorStart\x12\x0f.commonpb.Empty\x1a\x12.commonpb.Response\x12/\n" +
	"\vMonitorStop\x12\x0f.commonpb.Empty\x1a\x0f.commonpb.Empty\x12C\n" +
	"\x11MonitorListConfig\x12\x0f.commonpb.Empty\x1a\x1d.clientpb.MonitoringProviders\x12D\n" +
	"\x10MonitorAddConfig\x12\x1c.clientpb.MonitoringProvider\x1a\x12.commonpb.Response\x12D\n" +
	"\x10MonitorDelConfig\x12\x1c.clientpb.MonitoringProvider\x1a\x12.commonpb.Response\x12>\n" +
	"\x0eGetAIProviders\x12\x0f.commonpb.Empty\x1a\x1b.clientpb.AIProviderConfigs\x12@\n" +
	"\x12GetAIConversations\x12\x0f.commonpb.Empty\x1a\x19.clientpb.AIConversations\x12J\n" +
	"\x11GetAIConversation\x12\x1b.clientpb.AIConversationReq\x1a\x18.clientpb.AIConversation\x12H\n" +
	"\x12SaveAIConversation\x12\x18.clientpb.AIConversation\x1a\x18.clientpb.AIConversation\x12D\n" +
	"\x14DeleteAIConversation\x12\x1b.clientpb.AIConversationReq\x1a\x0f.commonpb.Empty\x12Z\n" +
	"\x19GetAIConversationMessages\x12\x1b.clientpb.AIConversationReq\x1a .clientpb.AIConversationMessages\x12]\n" +
	"\x19SaveAIConversationMessage\x12\x1f.clientpb.AIConversationMessage\x1a\x1f.clientpb.AIConversationMessage\x12E\n" +
	"\x11StartMTLSListener\x12\x19.clientpb.MTLSListenerReq\x1a\x15.clientpb.ListenerJob\x12A\n" +
	"\x0fStartWGListener\x12\x17.clientpb.WGListenerReq\x1a\x15.clientpb.ListenerJob\x12C\n" +
	"\x10StartDNSListener\x12\x18.clientpb.DNSListenerReq\x1a\x15.clientpb.ListenerJob\x12F\n" +
	"\x12StartHTTPSListener\x12\x19.clientpb.HTTPListenerReq\x1a\x15.clientpb.ListenerJob\x12E\n" +
	"\x11StartHTTPListener\x12\x19.clientpb.HTTPListenerReq\x1a\x15.clientpb.ListenerJob\x120\n" +
	"\n" +
	"GetBeacons\x12\x0f.commonpb.Empty\x1a\x11.clientpb.Beacons\x12/\n" +
	"\tGetBeacon\x12\x10.clientpb.Beacon\x1a\x10.clientpb.Beacon\x12-\n" +
	"\bRmBeacon\x12\x10.clientpb.Beacon\x1a\x0f.commonpb.Empty\x129\n" +
	"\x0eGetBeaconTasks\x12\x10.clientpb.Beacon\x1a\x15.clientpb.BeaconTasks\x12B\n" +
	"\x14GetBeaconTaskContent\x12\x14.clientpb.BeaconTask\x1a\x14.clientpb.BeaconTask\x12>\n" +
	"\x10CancelBeaconTask\x12\x14.clientpb.BeaconTask\x1a\x14.clientpb.BeaconTask\x12N\n" +
	" UpdateBeaconIntegrityInformation\x12\x19.clientpb.BeaconIntegrity\x1a\x0f.commonpb.Empty\x12*\n" +
	"\aGetJobs\x12\x0f.commonpb.Empty\x1a\x0e.clientpb.Jobs\x122\n" +
	"\aKillJob\x12\x14.clientpb.KillJobReq\x1a\x11.clientpb.KillJob\x127\n" +
	"\vRestartJobs\x12\x17.clientpb.RestartJobReq\x1a\x0f.commonpb.Empty\x12O\n" +
	"\x16StartTCPStagerListener\x12\x1b.clientpb.StagerListenerReq\x1a\x18.clientpb.StagerListener\x12)\n" +
	"\aLootAdd\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.Loot\x12)\n" +
	"\x06LootRm\x12\x0e.clientpb.Loot\x1a\x0f.commonpb.Empty\x12,\n" +
	"\n" +
	"LootUpdate\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.Loot\x12-\n" +
	"\vLootContent\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.Loot\x12-\n" +
	"\aLootAll\x12\x0f.commonpb.Empty\x1a\x11.clientpb.AllLoot\x12/\n" +
	"\x05Creds\x12\x0f.commonpb.Empty\x1a\x15.clientpb.Credentials\x122\n" +
	"\bCredsAdd\x12\x15.clientpb.Credentials\x1a\x0f.commonpb.Empty\x121\n" +
	"\aCredsRm\x12\x15.clientpb.Credentials\x1a\x0f.commonpb.Empty\x125\n" +
	"\vCredsUpdate\x12\x15.clientpb.Credentials\x1a\x0f.commonpb.Empty\x129\n" +
	"\vGetCredByID\x12\x14.clientpb.Credential\x1a\x14.clientpb.Credential\x12A\n" +
	"\x12GetCredsByHashType\x12\x14.clientpb.Credential\x1a\x15.clientpb.Credentials\x12J\n" +
	"\x1bGetPlaintextCredsByHashType\x12\x14.clientpb.Credential\x1a\x15.clientpb.Credentials\x12@\n" +
	"\x12CredsSniffHashType\x12\x14.clientpb.Credential\x1a\x14.clientpb.Credential\x12,\n" +
	"\x05Hosts\x12\x0f.commonpb.Empty\x1a\x12.clientpb.AllHosts\x12&\n" +
	"\x04Host\x12\x0e.clientpb.Host\x1a\x0e.clientpb.Host\x12)\n" +
	"\x06HostRm\x12\x0e.clientpb.Host\x1a\x0f.commonpb.Empty\x12+\n" +
	"\tHostIOCRm\x12\r.clientpb.IOC\x1a\x0f.commonpb.Empty\x125\n" +
	"\bGenerate\x12\x15.clientpb.GenerateReq\x1a\x12.clientpb.Generate\x12L\n" +
	"\x15GenerateSpoofMetadata\x12\".clientpb.GenerateSpoofMetadataReq\x1a\x0f.commonpb.Empty\x12R\n" +
	"\x10GenerateExternal\x12\x1d.clientpb.ExternalGenerateReq\x1a\x1f.clientpb.ExternalImplantConfig\x12M\n" +
	"\x19GenerateExternalSaveBuild\x12\x1f.clientpb.ExternalImplantBinary\x1a\x0f.commonpb.Empty\x12Y\n" +
	"\x1eGenerateExternalGetBuildConfig\x12\x16.clientpb.ImplantBuild\x1a\x1f.clientpb.ExternalImplantConfig\x12?\n" +
	"\rGenerateStage\x12\x1a.clientpb.GenerateStageReq\x1a\x12.clientpb.Generate\x12?\n" +
	"\x11StageImplantBuild\x12\x19.clientpb.ImplantStageReq\x1a\x0f.commonpb.Empty\x12=\n" +
	"\x11GetHTTPC2Profiles\x12\x0f.commonpb.Empty\x1a\x17.clientpb.HTTPC2Configs\x12H\n" +
	"\x16GetHTTPC2ProfileByName\x12\x16.clientpb.C2ProfileReq\x1a\x16.clientpb.HTTPC2Config\x12?\n" +
	"\x11SaveHTTPC2Profile\x12\x19.clientpb.HTTPC2ConfigReq\x1a\x0f.commonpb.Empty\x127\n" +
	"\x0fBuilderRegister\x12\x11.clientpb.Builder\x1a\x0f.clientpb.Event0\x01\x122\n" +
	"\x0eBuilderTrigger\x12\x0f.clientpb.Event\x1a\x0f.commonpb.Empty\x12/\n" +
	"\bBuilders\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Builders\x12J\n" +
	"\x12GetCertificateInfo\x12\x19.clientpb.CertificatesReq\x1a\x19.clientpb.CertificateInfo\x12R\n" +
	"\x1bGetCertificateAuthorityInfo\x12\x0f.commonpb.Empty\x1a\".clientpb.CertificateAuthorityInfo\x128\n" +
	"\x05Crack\x12\x16.clientpb.CrackCommand\x1a\x17.clientpb.CrackResponse\x12A\n" +
	"\x14CrackstationRegister\x12\x16.clientpb.Crackstation\x1a\x0f.clientpb.Event0\x01\x127\n" +
	"\x13CrackstationTrigger\x12\x0f.clientpb.Event\x1a\x0f.commonpb.Empty\x12B\n" +
	"\x15CrackstationBenchmark\x12\x18.clientpb.CrackBenchmark\x1a\x0f.commonpb.Empty\x129\n" +
	"\rCrackstations\x12\x0f.commonpb.Empty\x1a\x17.clientpb.Crackstations\x129\n" +
	"\rCrackTaskByID\x12\x13.clientpb.CrackTask\x1a\x13.clientpb.CrackTask\x127\n" +
	"\x0fCrackTaskUpdate\x12\x13.clientpb.CrackTask\x1a\x0f.commonpb.Empty\x12;\n" +
	"\x0eCrackFilesList\x12\x13.clientpb.CrackFile\x1a\x14.clientpb.CrackFiles\x12;\n" +
	"\x0fCrackFileCreate\x12\x13.clientpb.CrackFile\x1a\x13.clientpb.CrackFile\x12A\n" +
	"\x14CrackFileChunkUpload\x12\x18.clientpb.CrackFileChunk\x1a\x0f.commonpb.Empty\x12L\n" +
	"\x16CrackFileChunkDownload\x12\x18.clientpb.CrackFileChunk\x1a\x18.clientpb.CrackFileChunk\x129\n" +
	"\x11CrackFileComplete\x12\x13.clientpb.CrackFile\x1a\x0f.commonpb.Empty\x127\n" +
	"\x0fCrackFileDelete\x12\x13.clientpb.CrackFile\x1a\x0f.commonpb.Empty\x129\n" +
	"\n" +
	"Regenerate\x12\x17.clientpb.RegenerateReq\x1a\x12.clientpb.Generate\x129\n" +
	"\rImplantBuilds\x12\x0f.commonpb.Empty\x1a\x17.clientpb.ImplantBuilds\x12:\n" +
	"\x12DeleteImplantBuild\x12\x13.clientpb.DeleteReq\x1a\x0f.commonpb.Empty\x12/\n" +
	"\bCanaries\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Canaries\x12C\n" +
	"\x16GenerateWGClientConfig\x12\x0f.commonpb.Empty\x1a\x18.clientpb.WGClientConfig\x129\n" +
	"\x10GenerateUniqueIP\x12\x0f.commonpb.Empty\x1a\x14.clientpb.UniqueWGIP\x12=\n" +
	"\x0fImplantProfiles\x12\x0f.commonpb.Empty\x1a\x19.clientpb.ImplantProfiles\x12<\n" +
	"\x14DeleteImplantProfile\x12\x13.clientpb.DeleteReq\x1a\x0f.commonpb.Empty\x12H\n" +
	"\x12SaveImplantProfile\x12\x18.clientpb.ImplantProfile\x1a\x18.clientpb.ImplantProfile\x12A\n" +
	"\fShellcodeRDI\x12\x19.clientpb.ShellcodeRDIReq\x1a\x16.clientpb.ShellcodeRDI\x122\n" +
	"\vGetCompiler\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Compiler\x12K\n" +
	"\x10ShellcodeEncoder\x12\x1c.clientpb.ShellcodeEncodeReq\x1a\x19.clientpb.ShellcodeEncode\x12E\n" +
	"\x13ShellcodeEncoderMap\x12\x0f.commonpb.Empty\x1a\x1d.clientpb.ShellcodeEncoderMap\x12A\n" +
	"\x11TrafficEncoderMap\x12\x0f.commonpb.Empty\x1a\x1b.clientpb.TrafficEncoderMap\x12L\n" +
	"\x11TrafficEncoderAdd\x12\x18.clientpb.TrafficEncoder\x1a\x1d.clientpb.TrafficEncoderTests\x12=\n" +
	"\x10TrafficEncoderRm\x12\x18.clientpb.TrafficEncoder\x1a\x0f.commonpb.Empty\x12/\n" +
	"\bWebsites\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Websites\x12/\n" +
	"\aWebsite\x12\x11.clientpb.Website\x1a\x11.clientpb.Website\x123\n" +
	"\rWebsiteRemove\x12\x11.clientpb.Website\x1a\x0f.commonpb.Empty\x12C\n" +
	"\x11WebsiteAddContent\x12\x1b.clientpb.WebsiteAddContent\x1a\x11.clientpb.Website\x12F\n" +
	"\x14WebsiteUpdateContent\x12\x1b.clientpb.WebsiteAddContent\x1a\x11.clientpb.Website\x12I\n" +
	"\x14WebsiteRemoveContent\x12\x1e.clientpb.WebsiteRemoveContent\x1a\x11.clientpb.Website\x12(\n" +
	"\x04Ping\x12\x0f.phantompb.Ping\x1a\x0f.phantompb.Ping\x12%\n" +
	"\x02Ps\x12\x10.phantompb.PsReq\x1a\r.phantompb.Ps\x12:\n" +
	"\tTerminate\x12\x17.phantompb.TerminateReq\x1a\x14.phantompb.Terminate\x127\n" +
	"\bIfconfig\x12\x16.phantompb.IfconfigReq\x1a\x13.phantompb.Ifconfig\x124\n" +
	"\aNetstat\x12\x15.phantompb.NetstatReq\x1a\x12.phantompb.Netstat\x12%\n" +
	"\x02Ls\x12\x10.phantompb.LsReq\x1a\r.phantompb.Ls\x12&\n" +
	"\x02Cd\x12\x10.phantompb.CdReq\x1a\x0e.phantompb.Pwd\x12(\n" +
	"\x03Pwd\x12\x11.phantompb.PwdReq\x1a\x0e.phantompb.Pwd\x12%\n" +
	"\x02Mv\x12\x10.phantompb.MvReq\x1a\r.phantompb.Mv\x12%\n" +
	"\x02Cp\x12\x10.phantompb.CpReq\x1a\r.phantompb.Cp\x12%\n" +
	"\x02Rm\x12\x10.phantompb.RmReq\x1a\r.phantompb.Rm\x12.\n" +
	"\x05Mkdir\x12\x13.phantompb.MkdirReq\x1a\x10.phantompb.Mkdir\x127\n" +
	"\bDownload\x12\x16.phantompb.DownloadReq\x1a\x13.phantompb.Download\x121\n" +
	"\x06Upload\x12\x14.phantompb.UploadReq\x1a\x11.phantompb.Upload\x12+\n" +
	"\x04Grep\x12\x12.phantompb.GrepReq\x1a\x0f.phantompb.Grep\x12.\n" +
	"\x05Chmod\x12\x13.phantompb.ChmodReq\x1a\x10.phantompb.Chmod\x12.\n" +
	"\x05Chown\x12\x13.phantompb.ChownReq\x1a\x10.phantompb.Chown\x124\n" +
	"\aChtimes\x12\x15.phantompb.ChtimesReq\x1a\x12.phantompb.Chtimes\x129\n" +
	"\fMemfilesList\x12\x1a.phantompb.MemfilesListReq\x1a\r.phantompb.Ls\x12@\n" +
	"\vMemfilesAdd\x12\x19.phantompb.MemfilesAddReq\x1a\x16.phantompb.MemfilesAdd\x12=\n" +
	"\n" +
	"MemfilesRm\x12\x18.phantompb.MemfilesRmReq\x1a\x15.phantompb.MemfilesRm\x12.\n" +
	"\x05Mount\x12\x13.phantompb.MountReq\x1a\x10.phantompb.Mount\x12@\n" +
	"\vProcessDump\x12\x19.phantompb.ProcessDumpReq\x1a\x16.phantompb.ProcessDump\x12.\n" +
	"\x05RunAs\x12\x13.phantompb.RunAsReq\x1a\x10.phantompb.RunAs\x12@\n" +
	"\vImpersonate\x12\x19.phantompb.ImpersonateReq\x1a\x16.phantompb.Impersonate\x12:\n" +
	"\tRevToSelf\x12\x17.phantompb.RevToSelfReq\x1a\x14.phantompb.RevToSelf\x129\n" +
	"\tGetSystem\x12\x16.clientpb.GetSystemReq\x1a\x14.phantompb.GetSystem\x12+\n" +
	"\x04Task\x12\x12.phantompb.TaskReq\x1a\x0f.phantompb.Task\x12(\n" +
	"\x03Msf\x12\x10.clientpb.MSFReq\x1a\x0f.phantompb.Task\x124\n" +
	"\tMsfRemote\x12\x16.clientpb.MSFRemoteReq\x1a\x0f.phantompb.Task\x12L\n" +
	"\x0fExecuteAssembly\x12\x1d.phantompb.ExecuteAssemblyReq\x1a\x1a.phantompb.ExecuteAssembly\x123\n" +
	"\aMigrate\x12\x14.clientpb.MigrateReq\x1a\x12.phantompb.Migrate\x124\n" +
	"\aExecute\x12\x15.phantompb.ExecuteReq\x1a\x12.phantompb.Execute\x12B\n" +
	"\x0eExecuteWindows\x12\x1c.phantompb.ExecuteWindowsReq\x1a\x12.phantompb.Execute\x12L\n" +
	"\x0fExecuteChildren\x12\x1d.phantompb.ExecuteChildrenReq\x1a\x1a.phantompb.ExecuteChildren\x127\n" +
	"\bSideload\x12\x16.phantompb.SideloadReq\x1a\x13.phantompb.Sideload\x12=\n" +
	"\bSpawnDll\x12\x1c.phantompb.InvokeSpawnDllReq\x1a\x13.phantompb.SpawnDll\x12=\n" +
	"\n" +
	"Screenshot\x12\x18.phantompb.ScreenshotReq\x1a\x15.phantompb.Screenshot\x12R\n" +
	"\x11CurrentTokenOwner\x12\x1f.phantompb.CurrentTokenOwnerReq\x1a\x1c.phantompb.CurrentTokenOwner\x127\n" +
	"\bServices\x12\x16.phantompb.ServicesReq\x1a\x13.phantompb.Services\x12F\n" +
	"\rServiceDetail\x12\x1b.phantompb.ServiceDetailReq\x1a\x18.phantompb.ServiceDetail\x12N\n" +
	"\x12StartServiceByName\x12 .phantompb.StartServiceByNameReq\x1a\x16.phantompb.ServiceInfo\x12P\n" +
	"\x12PivotStartListener\x12 .phantompb.PivotStartListenerReq\x1a\x18.phantompb.PivotListener\x12E\n" +
	"\x11PivotStopListener\x12\x1f.phantompb.PivotStopListenerReq\x1a\x0f.commonpb.Empty\x12P\n" +
	"\x15PivotSessionListeners\x12\x1c.phantompb.PivotListenersReq\x1a\x19.phantompb.PivotListeners\x123\n" +
	"\n" +
	"PivotGraph\x12\x0f.commonpb.Empty\x1a\x14.clientpb.PivotGraph\x12B\n" +
	"\fStartService\x12\x1a.phantompb.StartServiceReq\x1a\x16.phantompb.ServiceInfo\x12@\n" +
	"\vStopService\x12\x19.phantompb.StopServiceReq\x1a\x16.phantompb.ServiceInfo\x12D\n" +
	"\rRemoveService\x12\x1b.phantompb.RemoveServiceReq\x1a\x16.phantompb.ServiceInfo\x12:\n" +
	"\tMakeToken\x12\x17.phantompb.MakeTokenReq\x1a\x14.phantompb.MakeToken\x12/\n" +
	"\x06GetEnv\x12\x11.phantompb.EnvReq\x1a\x12.phantompb.EnvInfo\x121\n" +
	"\x06SetEnv\x12\x14.phantompb.SetEnvReq\x1a\x11.phantompb.SetEnv\x127\n" +
	"\bUnsetEnv\x12\x16.phantompb.UnsetEnvReq\x1a\x13.phantompb.UnsetEnv\x125\n" +
	"\bBackdoor\x12\x15.clientpb.BackdoorReq\x1a\x12.clientpb.Backdoor\x12C\n" +
	"\fRegistryRead\x12\x1a.phantompb.RegistryReadReq\x1a\x17.phantompb.RegistryRead\x12F\n" +
	"\rRegistryWrite\x12\x1b.phantompb.RegistryWriteReq\x1a\x18.phantompb.RegistryWrite\x12R\n" +
	"\x11RegistryCreateKey\x12\x1f.phantompb.RegistryCreateKeyReq\x1a\x1c.phantompb.RegistryCreateKey\x12R\n" +
	"\x11RegistryDeleteKey\x12\x1f.phantompb.RegistryDeleteKeyReq\x1a\x1c.phantompb.RegistryDeleteKey\x12V\n" +
	"\x13RegistryListSubKeys\x12 .phantompb.RegistrySubKeyListReq\x1a\x1d.phantompb.RegistrySubKeyList\x12U\n" +
	"\x12RegistryListValues\x12 .phantompb.RegistryListValuesReq\x1a\x1d.phantompb.RegistryValuesList\x12O\n" +
	"\x10RegistryReadHive\x12\x1e.phantompb.RegistryReadHiveReq\x1a\x1b.phantompb.RegistryReadHive\x12@\n" +
	"\rRunSSHCommand\x12\x18.phantompb.SSHCommandReq\x1a\x15.phantompb.SSHCommand\x128\n" +
	"\tHijackDLL\x12\x16.clientpb.DllHijackReq\x1a\x13.clientpb.DllHijack\x127\n" +
	"\bGetPrivs\x12\x16.phantompb.GetPrivsReq\x1a\x13.phantompb.GetPrivs\x12Y\n" +
	"\x15StartRportFwdListener\x12#.phantompb.RportFwdStartListenerReq\x1a\x1b.phantompb.RportFwdListener\x12U\n" +
	"\x14GetRportFwdListeners\x12\x1f.phantompb.RportFwdListenersReq\x1a\x1c.phantompb.RportFwdListeners\x12W\n" +
	"\x14StopRportFwdListener\x12\".phantompb.RportFwdStopListenerReq\x1a\x1b.phantompb.RportFwdListener\x12=\n" +
	"\vOpenSession\x12\x16.phantompb.OpenSession\x1a\x16.phantompb.OpenSession\x128\n" +
	"\fCloseSession\x12\x17.phantompb.CloseSession\x1a\x0f.commonpb.Empty\x12R\n" +
	"\x11RegisterExtension\x12\x1f.phantompb.RegisterExtensionReq\x1a\x1c.phantompb.RegisterExtension\x12F\n" +
	"\rCallExtension\x12\x1b.phantompb.CallExtensionReq\x1a\x18.phantompb.CallExtension\x12I\n" +
	"\x0eListExtensions\x12\x1c.phantompb.ListExtensionsReq\x1a\x19.phantompb.ListExtensions\x12^\n" +
	"\x15RegisterWasmExtension\x12#.phantompb.RegisterWasmExtensionReq\x1a .phantompb.RegisterWasmExtension\x12U\n" +
	"\x12ListWasmExtensions\x12 .phantompb.ListWasmExtensionsReq\x1a\x1d.phantompb.ListWasmExtensions\x12R\n" +
	"\x11ExecWasmExtension\x12\x1f.phantompb.ExecWasmExtensionReq\x1a\x1c.phantompb.ExecWasmExtension\x12P\n" +
	"\x12WGStartPortForward\x12 .phantompb.WGPortForwardStartReq\x1a\x18.phantompb.WGPortForward\x12N\n" +
	"\x11WGStopPortForward\x12\x1f.phantompb.WGPortForwardStopReq\x1a\x18.phantompb.WGPortForward\x12>\n" +
	"\fWGStartSocks\x12\x1a.phantompb.WGSocksStartReq\x1a\x12.phantompb.WGSocks\x12<\n" +
	"\vWGStopSocks\x12\x19.phantompb.WGSocksStopReq\x1a\x12.phantompb.WGSocks\x12M\n" +
	"\x10WGListForwarders\x12\x1d.phantompb.WGTCPForwardersReq\x1a\x1a.phantompb.WGTCPForwarders\x12M\n" +
	"\x12WGListSocksServers\x12\x1c.phantompb.WGSocksServersReq\x1a\x19.phantompb.WGSocksServers\x12.\n" +
	"\x05Shell\x12\x13.phantompb.ShellReq\x1a\x10.phantompb.Shell\x129\n" +
	"\vShellResize\x12\x19.phantompb.ShellResizeReq\x1a\x0f.commonpb.Empty\x124\n" +
	"\aPortfwd\x12\x15.phantompb.PortfwdReq\x1a\x12.phantompb.Portfwd\x121\n" +
	"\vCreateSocks\x12\x10.phantompb.Socks\x1a\x10.phantompb.Socks\x12/\n" +
	"\n" +
	"CloseSocks\x12\x10.phantompb.Socks\x1a\x0f.commonpb.Empty\x12<\n" +
	"\n" +
	"SocksProxy\x12\x14.phantompb.SocksData\x1a\x14.phantompb.SocksData(\x010\x01\x124\n" +
	"\fCreateTunnel\x12\x11.phantompb.Tunnel\x1a\x11.phantompb.Tunnel\x121\n" +
	"\vCloseTunnel\x12\x11.phantompb.Tunnel\x1a\x0f.commonpb.Empty\x12>\n" +
	"\n" +
	"TunnelData\x12\x15.phantompb.TunnelData\x1a\x15.phantompb.TunnelData(\x010\x01\x12,\n" +
	"\x06Events\x12\x0f.commonpb.Empty\x1a\x0f.clientpb.Event0\x01\x12=\n" +
	"\fGetAuditLogs\x12\x18.clientpb.AuditLogFilter\x1a\x13.clientpb.AuditLogs\x12>\n" +
	"\x10CreateEngagement\x12\x14.clientpb.Engagement\x1a\x14.clientpb.Engagement\x128\n" +
	"\x0eGetEngagements\x12\x0f.commonpb.Empty\x1a\x15.clientpb.Engagements\x12>\n" +
	"\rGetEngagement\x12\x17.clientpb.EngagementReq\x1a\x14.clientpb.Engagement\x12>\n" +
	"\x10UpdateEngagement\x12\x14.clientpb.Engagement\x1a\x14.clientpb.Engagement\x12<\n" +
	"\x10DeleteEngagement\x12\x17.clientpb.EngagementReq\x1a\x0f.commonpb.Empty\x12G\n" +
	"\x19AssignSessionToEngagement\x12\x19.clientpb.AssignTargetReq\x1a\x0f.commonpb.Empty\x12F\n" +
	"\x18AssignBeaconToEngagement\x12\x19.clientpb.AssignTargetReq\x1a\x0f.commonpb.Empty\x12I\n" +
	"\x1bRemoveSessionFromEngagement\x12\x19.clientpb.AssignTargetReq\x1a\x0f.commonpb.Empty\x12H\n" +
	"\x1aRemoveBeaconFromEngagement\x12\x19.clientpb.AssignTargetReq\x1a\x0f.commonpb.Empty\x122\n" +
	"\n" +
	"AddFinding\x12\x11.clientpb.Finding\x1a\x11.clientpb.Finding\x125\n" +
	"\rUpdateFinding\x12\x11.clientpb.Finding\x1a\x11.clientpb.Finding\x123\n" +
	"\rDeleteFinding\x12\x11.clientpb.Finding\x1a\x0f.commonpb.EmptyB5Z3github.com/cryptdefender3232/phantom/protobuf/rpcpbb\x06proto3"

var file_rpcpb_services_proto_goTypes = []any{
	(*commonpb.Empty)(nil),                     // 0: commonpb.Empty
	(*clientpb.ClientLogData)(nil),             // 1: clientpb.ClientLogData
	(*phantompb.KillReq)(nil),                  // 2: phantompb.KillReq
	(*phantompb.ReconfigureReq)(nil),           // 3: phantompb.ReconfigureReq
	(*clientpb.RenameReq)(nil),                 // 4: clientpb.RenameReq
	(*clientpb.MonitoringProvider)(nil),        // 5: clientpb.MonitoringProvider
	(*clientpb.AIConversationReq)(nil),         // 6: clientpb.AIConversationReq
	(*clientpb.AIConversation)(nil),            // 7: clientpb.AIConversation
	(*clientpb.AIConversationMessage)(nil),     // 8: clientpb.AIConversationMessage
	(*clientpb.MTLSListenerReq)(nil),           // 9: clientpb.MTLSListenerReq
	(*clientpb.WGListenerReq)(nil),             // 10: clientpb.WGListenerReq
	(*clientpb.DNSListenerReq)(nil),            // 11: clientpb.DNSListenerReq
	(*clientpb.HTTPListenerReq)(nil),           // 12: clientpb.HTTPListenerReq
	(*clientpb.Beacon)(nil),                    // 13: clientpb.Beacon
	(*clientpb.BeaconTask)(nil),                // 14: clientpb.BeaconTask
	(*clientpb.BeaconIntegrity)(nil),           // 15: clientpb.BeaconIntegrity
	(*clientpb.KillJobReq)(nil),                // 16: clientpb.KillJobReq
	(*clientpb.RestartJobReq)(nil),             // 17: clientpb.RestartJobReq
	(*clientpb.StagerListenerReq)(nil),         // 18: clientpb.StagerListenerReq
	(*clientpb.Loot)(nil),                      // 19: clientpb.Loot
	(*clientpb.Credentials)(nil),               // 20: clientpb.Credentials
	(*clientpb.Credential)(nil),                // 21: clientpb.Credential
	(*clientpb.Host)(nil),                      // 22: clientpb.Host
	(*clientpb.IOC)(nil),                       // 23: clientpb.IOC
	(*clientpb.GenerateReq)(nil),               // 24: clientpb.GenerateReq
	(*clientpb.GenerateSpoofMetadataReq)(nil),  // 25: clientpb.GenerateSpoofMetadataReq
	(*clientpb.ExternalGenerateReq)(nil),       // 26: clientpb.ExternalGenerateReq
	(*clientpb.ExternalImplantBinary)(nil),     // 27: clientpb.ExternalImplantBinary
	(*clientpb.ImplantBuild)(nil),              // 28: clientpb.ImplantBuild
	(*clientpb.GenerateStageReq)(nil),          // 29: clientpb.GenerateStageReq
	(*clientpb.ImplantStageReq)(nil),           // 30: clientpb.ImplantStageReq
	(*clientpb.C2ProfileReq)(nil),              // 31: clientpb.C2ProfileReq
	(*clientpb.HTTPC2ConfigReq)(nil),           // 32: clientpb.HTTPC2ConfigReq
	(*clientpb.Builder)(nil),                   // 33: clientpb.Builder
	(*clientpb.Event)(nil),                     // 34: clientpb.Event
	(*clientpb.CertificatesReq)(nil),           // 35: clientpb.CertificatesReq
	(*clientpb.CrackCommand)(nil),              // 36: clientpb.CrackCommand
	(*clientpb.Crackstation)(nil),              // 37: clientpb.Crackstation
	(*clientpb.CrackBenchmark)(nil),            // 38: clientpb.CrackBenchmark
	(*clientpb.CrackTask)(nil),                 // 39: clientpb.CrackTask
	(*clientpb.CrackFile)(nil),                 // 40: clientpb.CrackFile
	(*clientpb.CrackFileChunk)(nil),            // 41: clientpb.CrackFileChunk
	(*clientpb.RegenerateReq)(nil),             // 42: clientpb.RegenerateReq
	(*clientpb.DeleteReq)(nil),                 // 43: clientpb.DeleteReq
	(*clientpb.ImplantProfile)(nil),            // 44: clientpb.ImplantProfile
	(*clientpb.ShellcodeRDIReq)(nil),           // 45: clientpb.ShellcodeRDIReq
	(*clientpb.ShellcodeEncodeReq)(nil),        // 46: clientpb.ShellcodeEncodeReq
	(*clientpb.TrafficEncoder)(nil),            // 47: clientpb.TrafficEncoder
	(*clientpb.Website)(nil),                   // 48: clientpb.Website
	(*clientpb.WebsiteAddContent)(nil),         // 49: clientpb.WebsiteAddContent
	(*clientpb.WebsiteRemoveContent)(nil),      // 50: clientpb.WebsiteRemoveContent
	(*phantompb.Ping)(nil),                     // 51: phantompb.Ping
	(*phantompb.PsReq)(nil),                    // 52: phantompb.PsReq
	(*phantompb.TerminateReq)(nil),             // 53: phantompb.TerminateReq
	(*phantompb.IfconfigReq)(nil),              // 54: phantompb.IfconfigReq
	(*phantompb.NetstatReq)(nil),               // 55: phantompb.NetstatReq
	(*phantompb.LsReq)(nil),                    // 56: phantompb.LsReq
	(*phantompb.CdReq)(nil),                    // 57: phantompb.CdReq
	(*phantompb.PwdReq)(nil),                   // 58: phantompb.PwdReq
	(*phantompb.MvReq)(nil),                    // 59: phantompb.MvReq
	(*phantompb.CpReq)(nil),                    // 60: phantompb.CpReq
	(*phantompb.RmReq)(nil),                    // 61: phantompb.RmReq
	(*phantompb.MkdirReq)(nil),                 // 62: phantompb.MkdirReq
	(*phantompb.DownloadReq)(nil),              // 63: phantompb.DownloadReq
	(*phantompb.UploadReq)(nil),                // 64: phantompb.UploadReq
	(*phantompb.GrepReq)(nil),                  // 65: phantompb.GrepReq
	(*phantompb.ChmodReq)(nil),                 // 66: phantompb.ChmodReq
	(*phantompb.ChownReq)(nil),                 // 67: phantompb.ChownReq
	(*phantompb.ChtimesReq)(nil),               // 68: phantompb.ChtimesReq
	(*phantompb.MemfilesListReq)(nil),          // 69: phantompb.MemfilesListReq
	(*phantompb.MemfilesAddReq)(nil),           // 70: phantompb.MemfilesAddReq
	(*phantompb.MemfilesRmReq)(nil),            // 71: phantompb.MemfilesRmReq
	(*phantompb.MountReq)(nil),                 // 72: phantompb.MountReq
	(*phantompb.ProcessDumpReq)(nil),           // 73: phantompb.ProcessDumpReq
	(*phantompb.RunAsReq)(nil),                 // 74: phantompb.RunAsReq
	(*phantompb.ImpersonateReq)(nil),           // 75: phantompb.ImpersonateReq
	(*phantompb.RevToSelfReq)(nil),             // 76: phantompb.RevToSelfReq
	(*clientpb.GetSystemReq)(nil),              // 77: clientpb.GetSystemReq
	(*phantompb.TaskReq)(nil),                  // 78: phantompb.TaskReq
	(*clientpb.MSFReq)(nil),                    // 79: clientpb.MSFReq
	(*clientpb.MSFRemoteReq)(nil),              // 80: clientpb.MSFRemoteReq
	(*phantompb.ExecuteAssemblyReq)(nil),       // 81: phantompb.ExecuteAssemblyReq
	(*clientpb.MigrateReq)(nil),                // 82: clientpb.MigrateReq
	(*phantompb.ExecuteReq)(nil),               // 83: phantompb.ExecuteReq
	(*phantompb.ExecuteWindowsReq)(nil),        // 84: phantompb.ExecuteWindowsReq
	(*phantompb.ExecuteChildrenReq)(nil),       // 85: phantompb.ExecuteChildrenReq
	(*phantompb.SideloadReq)(nil),              // 86: phantompb.SideloadReq
	(*phantompb.InvokeSpawnDllReq)(nil),        // 87: phantompb.InvokeSpawnDllReq
	(*phantompb.ScreenshotReq)(nil),            // 88: phantompb.ScreenshotReq
	(*phantompb.CurrentTokenOwnerReq)(nil),     // 89: phantompb.CurrentTokenOwnerReq
	(*phantompb.ServicesReq)(nil),              // 90: phantompb.ServicesReq
	(*phantompb.ServiceDetailReq)(nil),         // 91: phantompb.ServiceDetailReq
	(*phantompb.StartServiceByNameReq)(nil),    // 92: phantompb.StartServiceByNameReq
	(*phantompb.PivotStartListenerReq)(nil),    // 93: phantompb.PivotStartListenerReq
	(*phantompb.PivotStopListenerReq)(nil),     // 94: phantompb.PivotStopListenerReq
	(*phantompb.PivotListenersReq)(nil),        // 95: phantompb.PivotListenersReq
	(*phantompb.StartServiceReq)(nil),          // 96: phantompb.StartServiceReq
	(*phantompb.StopServiceReq)(nil),           // 97: phantompb.StopServiceReq
	(*phantompb.RemoveServiceReq)(nil),         // 98: phantompb.RemoveServiceReq
	(*phantompb.MakeTokenReq)(nil),             // 99: phantompb.MakeTokenReq
	(*phantompb.EnvReq)(nil),                   // 100: phantompb.EnvReq
	(*phantompb.SetEnvReq)(nil),                // 101: phantompb.SetEnvReq
	(*phantompb.UnsetEnvReq)(nil),              // 102: phantompb.UnsetEnvReq
	(*clientpb.BackdoorReq)(nil),               // 103: clientpb.BackdoorReq
	(*phantompb.RegistryReadReq)(nil),          // 104: phantompb.RegistryReadReq
	(*phantompb.RegistryWriteReq)(nil),         // 105: phantompb.RegistryWriteReq
	(*phantompb.RegistryCreateKeyReq)(nil),     // 106: phantompb.RegistryCreateKeyReq
	(*phantompb.RegistryDeleteKeyReq)(nil),     // 107: phantompb.RegistryDeleteKeyReq
	(*phantompb.RegistrySubKeyListReq)(nil),    // 108: phantompb.RegistrySubKeyListReq
	(*phantompb.RegistryListValuesReq)(nil),    // 109: phantompb.RegistryListValuesReq
	(*phantompb.RegistryReadHiveReq)(nil),      // 110: phantompb.RegistryReadHiveReq
	(*phantompb.SSHCommandReq)(nil),            // 111: phantompb.SSHCommandReq
	(*clientpb.DllHijackReq)(nil),              // 112: clientpb.DllHijackReq
	(*phantompb.GetPrivsReq)(nil),              // 113: phantompb.GetPrivsReq
	(*phantompb.RportFwdStartListenerReq)(nil), // 114: phantompb.RportFwdStartListenerReq
	(*phantompb.RportFwdListenersReq)(nil),     // 115: phantompb.RportFwdListenersReq
	(*phantompb.RportFwdStopListenerReq)(nil),  // 116: phantompb.RportFwdStopListenerReq
	(*phantompb.OpenSession)(nil),              // 117: phantompb.OpenSession
	(*phantompb.CloseSession)(nil),             // 118: phantompb.CloseSession
	(*phantompb.RegisterExtensionReq)(nil),     // 119: phantompb.RegisterExtensionReq
	(*phantompb.CallExtensionReq)(nil),         // 120: phantompb.CallExtensionReq
	(*phantompb.ListExtensionsReq)(nil),        // 121: phantompb.ListExtensionsReq
	(*phantompb.RegisterWasmExtensionReq)(nil), // 122: phantompb.RegisterWasmExtensionReq
	(*phantompb.ListWasmExtensionsReq)(nil),    // 123: phantompb.ListWasmExtensionsReq
	(*phantompb.ExecWasmExtensionReq)(nil),     // 124: phantompb.ExecWasmExtensionReq
	(*phantompb.WGPortForwardStartReq)(nil),    // 125: phantompb.WGPortForwardStartReq
	(*phantompb.WGPortForwardStopReq)(nil),     // 126: phantompb.WGPortForwardStopReq
	(*phantompb.WGSocksStartReq)(nil),          // 127: phantompb.WGSocksStartReq
	(*phantompb.WGSocksStopReq)(nil),           // 128: phantompb.WGSocksStopReq
	(*phantompb.WGTCPForwardersReq)(nil),       // 129: phantompb.WGTCPForwardersReq
	(*phantompb.WGSocksServersReq)(nil),        // 130: phantompb.WGSocksServersReq
	(*phantompb.ShellReq)(nil),                 // 131: phantompb.ShellReq
	(*phantompb.ShellResizeReq)(nil),           // 132: phantompb.ShellResizeReq
	(*phantompb.PortfwdReq)(nil),               // 133: phantompb.PortfwdReq
	(*phantompb.Socks)(nil),                    // 134: phantompb.Socks
	(*phantompb.SocksData)(nil),                // 135: phantompb.SocksData
	(*phantompb.Tunnel)(nil),                   // 136: phantompb.Tunnel
	(*phantompb.TunnelData)(nil),               // 137: phantompb.TunnelData
	(*clientpb.AuditLogFilter)(nil),            // 138: clientpb.AuditLogFilter
	(*clientpb.Engagement)(nil),                // 139: clientpb.Engagement
	(*clientpb.EngagementReq)(nil),             // 140: clientpb.EngagementReq
	(*clientpb.AssignTargetReq)(nil),           // 141: clientpb.AssignTargetReq
	(*clientpb.Finding)(nil),                   // 142: clientpb.Finding
	(*clientpb.Version)(nil),                   // 143: clientpb.Version
	(*clientpb.Operators)(nil),                 // 144: clientpb.Operators
	(*phantompb.Reconfigure)(nil),              // 145: phantompb.Reconfigure
	(*clientpb.Sessions)(nil),                  // 146: clientpb.Sessions
	(*commonpb.Response)(nil),                  // 147: commonpb.Response
	(*clientpb.MonitoringProviders)(nil),       // 148: clientpb.MonitoringProviders
	(*clientpb.AIProviderConfigs)(nil),         // 149: clientpb.AIProviderConfigs
	(*clientpb.AIConversations)(nil),           // 150: clientpb.AIConversations
	(*clientpb.AIConversationMessages)(nil),    // 151: clientpb.AIConversationMessages
	(*clientpb.ListenerJob)(nil),               // 152: clientpb.ListenerJob
	(*clientpb.Beacons)(nil),                   // 153: clientpb.Beacons
	(*clientpb.BeaconTasks)(nil),               // 154: clientpb.BeaconTasks
	(*clientpb.Jobs)(nil),                      // 155: clientpb.Jobs
	(*clientpb.KillJob)(nil),                   // 156: clientpb.KillJob
	(*clientpb.StagerListener)(nil),            // 157: clientpb.StagerListener
	(*clientpb.AllLoot)(nil),                   // 158: clientpb.AllLoot
	(*clientpb.AllHosts)(nil),                  // 159: clientpb.AllHosts
	(*clientpb.Generate)(nil),                  // 160: clientpb.Generate
	(*clientpb.ExternalImplantConfig)(nil),     // 161: clientpb.ExternalImplantConfig
	(*clientpb.HTTPC2Configs)(nil),             // 162: clientpb.HTTPC2Configs
	(*clientpb.HTTPC2Config)(nil),              // 163: clientpb.HTTPC2Config
	(*clientpb.Builders)(nil),                  // 164: clientpb.Builders
	(*clientpb.CertificateInfo)(nil),           // 165: clientpb.CertificateInfo
	(*clientpb.CertificateAuthorityInfo)(nil),  // 166: clientpb.CertificateAuthorityInfo
	(*clientpb.CrackResponse)(nil),             // 167: clientpb.CrackResponse
	(*clientpb.Crackstations)(nil),             // 168: clientpb.Crackstations
	(*clientpb.CrackFiles)(nil),                // 169: clientpb.CrackFiles
	(*clientpb.ImplantBuilds)(nil),             // 170: clientpb.ImplantBuilds
	(*clientpb.Canaries)(nil),                  // 171: clientpb.Canaries
	(*clientpb.WGClientConfig)(nil),            // 172: clientpb.WGClientConfig
	(*clientpb.UniqueWGIP)(nil),                // 173: clientpb.UniqueWGIP
	(*clientpb.ImplantProfiles)(nil),           // 174: clientpb.ImplantProfiles
	(*clientpb.ShellcodeRDI)(nil),              // 175: clientpb.ShellcodeRDI
	(*clientpb.Compiler)(nil),                  // 176: clientpb.Compiler
	(*clientpb.ShellcodeEncode)(nil),           // 177: clientpb.ShellcodeEncode
	(*clientpb.ShellcodeEncoderMap)(nil),       // 178: clientpb.ShellcodeEncoderMap
	(*clientpb.TrafficEncoderMap)(nil),         // 179: clientpb.TrafficEncoderMap
	(*clientpb.TrafficEncoderTests)(nil),       // 180: clientpb.TrafficEncoderTests
	(*clientpb.Websites)(nil),                  // 181: clientpb.Websites
	(*phantompb.Ps)(nil),                       // 182: phantompb.Ps
	(*phantompb.Terminate)(nil),                // 183: phantompb.Terminate
	(*phantompb.Ifconfig)(nil),                 // 184: phantompb.Ifconfig
	(*phantompb.Netstat)(nil),                  // 185: phantompb.Netstat
	(*phantompb.Ls)(nil),                       // 186: phantompb.Ls
	(*phantompb.Pwd)(nil),                      // 187: phantompb.Pwd
	(*phantompb.Mv)(nil),                       // 188: phantompb.Mv
	(*phantompb.Cp)(nil),                       // 189: phantompb.Cp
	(*phantompb.Rm)(nil),                       // 190: phantompb.Rm
	(*phantompb.Mkdir)(nil),                    // 191: phantompb.Mkdir
	(*phantompb.Download)(nil),                 // 192: phantompb.Download
	(*phantompb.Upload)(nil),                   // 193: phantompb.Upload
	(*phantompb.Grep)(nil),                     // 194: phantompb.Grep
	(*phantompb.Chmod)(nil),                    // 195: phantompb.Chmod
	(*phantompb.Chown)(nil),                    // 196: phantompb.Chown
	(*phantompb.Chtimes)(nil),                  // 197: phantompb.Chtimes
	(*phantompb.MemfilesAdd)(nil),              // 198: phantompb.MemfilesAdd
	(*phantompb.MemfilesRm)(nil),               // 199: phantompb.MemfilesRm
	(*phantompb.Mount)(nil),                    // 200: phantompb.Mount
	(*phantompb.ProcessDump)(nil),              // 201: phantompb.ProcessDump
	(*phantompb.RunAs)(nil),                    // 202: phantompb.RunAs
	(*phantompb.Impersonate)(nil),              // 203: phantompb.Impersonate
	(*phantompb.RevToSelf)(nil),                // 204: phantompb.RevToSelf
	(*phantompb.GetSystem)(nil),                // 205: phantompb.GetSystem
	(*phantompb.Task)(nil),                     // 206: phantompb.Task
	(*phantompb.ExecuteAssembly)(nil),          // 207: phantompb.ExecuteAssembly
	(*phantompb.Migrate)(nil),                  // 208: phantompb.Migrate
	(*phantompb.Execute)(nil),                  // 209: phantompb.Execute
	(*phantompb.ExecuteChildren)(nil),          // 210: phantompb.ExecuteChildren
	(*phantompb.Sideload)(nil),                 // 211: phantompb.Sideload
	(*phantompb.SpawnDll)(nil),                 // 212: phantompb.SpawnDll
	(*phantompb.Screenshot)(nil),               // 213: phantompb.Screenshot
	(*phantompb.CurrentTokenOwner)(nil),        // 214: phantompb.CurrentTokenOwner
	(*phantompb.Services)(nil),                 // 215: phantompb.Services
	(*phantompb.ServiceDetail)(nil),            // 216: phantompb.ServiceDetail
	(*phantompb.ServiceInfo)(nil),              // 217: phantompb.ServiceInfo
	(*phantompb.PivotListener)(nil),            // 218: phantompb.PivotListener
	(*phantompb.PivotListeners)(nil),           // 219: phantompb.PivotListeners
	(*clientpb.PivotGraph)(nil),                // 220: clientpb.PivotGraph
	(*phantompb.MakeToken)(nil),                // 221: phantompb.MakeToken
	(*phantompb.EnvInfo)(nil),                  // 222: phantompb.EnvInfo
	(*phantompb.SetEnv)(nil),                   // 223: phantompb.SetEnv
	(*phantompb.UnsetEnv)(nil),                 // 224: phantompb.UnsetEnv
	(*clientpb.Backdoor)(nil),                  // 225: clientpb.Backdoor
	(*phantompb.RegistryRead)(nil),             // 226: phantompb.RegistryRead
	(*phantompb.RegistryWrite)(nil),            // 227: phantompb.RegistryWrite
	(*phantompb.RegistryCreateKey)(nil),        // 228: phantompb.RegistryCreateKey
	(*phantompb.RegistryDeleteKey)(nil),        // 229: phantompb.RegistryDeleteKey
	(*phantompb.RegistrySubKeyList)(nil),       // 230: phantompb.RegistrySubKeyList
	(*phantompb.RegistryValuesList)(nil),       // 231: phantompb.RegistryValuesList
	(*phantompb.RegistryReadHive)(nil),         // 232: phantompb.RegistryReadHive
	(*phantompb.SSHCommand)(nil),               // 233: phantompb.SSHCommand
	(*clientpb.DllHijack)(nil),                 // 234: clientpb.DllHijack
	(*phantompb.GetPrivs)(nil),                 // 235: phantompb.GetPrivs
	(*phantompb.RportFwdListener)(nil),         // 236: phantompb.RportFwdListener
	(*phantompb.RportFwdListeners)(nil),        // 237: phantompb.RportFwdListeners
	(*phantompb.RegisterExtension)(nil),        // 238: phantompb.RegisterExtension
	(*phantompb.CallExtension)(nil),            // 239: phantompb.CallExtension
	(*phantompb.ListExtensions)(nil),           // 240: phantompb.ListExtensions
	(*phantompb.RegisterWasmExtension)(nil),    // 241: phantompb.RegisterWasmExtension
	(*phantompb.ListWasmExtensions)(nil),       // 242: phantompb.ListWasmExtensions
	(*phantompb.ExecWasmExtension)(nil),        // 243: phantompb.ExecWasmExtension
	(*phantompb.WGPortForward)(nil),            // 244: phantompb.WGPortForward
	(*phantompb.WGSocks)(nil),                  // 245: phantompb.WGSocks
	(*phantompb.WGTCPForwarders)(nil),          // 246: phantompb.WGTCPForwarders
	(*phantompb.WGSocksServers)(nil),           // 247: phantompb.WGSocksServers
	(*phantompb.Shell)(nil),                    // 248: phantompb.Shell
	(*phantompb.Portfwd)(nil),                  // 249: phantompb.Portfwd
	(*clientpb.AuditLogs)(nil),                 // 250: clientpb.AuditLogs
	(*clientpb.Engagements)(nil),               // 251: clientpb.Engagements
}
var file_rpcpb_services_proto_depIdxs = []int32{
	0,   // 0: rpcpb.PhantomRPC.GetVersion:input_type -> commonpb.Empty
	1,   // 1: rpcpb.PhantomRPC.ClientLog:input_type -> clientpb.ClientLogData
	0,   // 2: rpcpb.PhantomRPC.GetOperators:input_type -> commonpb.Empty
	2,   // 3: rpcpb.PhantomRPC.Kill:input_type -> phantompb.KillReq
	3,   // 4: rpcpb.PhantomRPC.Reconfigure:input_type -> phantompb.ReconfigureReq
	4,   // 5: rpcpb.PhantomRPC.Rename:input_type -> clientpb.RenameReq
	0,   // 6: rpcpb.PhantomRPC.GetSessions:input_type -> commonpb.Empty
	0,   // 7: rpcpb.PhantomRPC.MonitorStart:input_type -> commonpb.Empty
	0,   // 8: rpcpb.PhantomRPC.MonitorStop:input_type -> commonpb.Empty
	0,   // 9: rpcpb.PhantomRPC.MonitorListConfig:input_type -> commonpb.Empty
	5,   // 10: rpcpb.PhantomRPC.MonitorAddConfig:input_type -> clientpb.MonitoringProvider
	5,   // 11: rpcpb.PhantomRPC.MonitorDelConfig:input_type -> clientpb.MonitoringProvider
	0,   // 12: rpcpb.PhantomRPC.GetAIProviders:input_type -> commonpb.Empty
	0,   // 13: rpcpb.PhantomRPC.GetAIConversations:input_type -> commonpb.Empty
	6,   // 14: rpcpb.PhantomRPC.GetAIConversation:input_type -> clientpb.AIConversationReq
	7,   // 15: rpcpb.PhantomRPC.SaveAIConversation:input_type -> clientpb.AIConversation
	6,   // 16: rpcpb.PhantomRPC.DeleteAIConversation:input_type -> clientpb.AIConversationReq
	6,   // 17: rpcpb.PhantomRPC.GetAIConversationMessages:input_type -> clientpb.AIConversationReq
	8,   // 18: rpcpb.PhantomRPC.SaveAIConversationMessage:input_type -> clientpb.AIConversationMessage
	9,   // 19: rpcpb.PhantomRPC.StartMTLSListener:input_type -> clientpb.MTLSListenerReq
	10,  // 20: rpcpb.PhantomRPC.StartWGListener:input_type -> clientpb.WGListenerReq
	11,  // 21: rpcpb.PhantomRPC.StartDNSListener:input_type -> clientpb.DNSListenerReq
	12,  // 22: rpcpb.PhantomRPC.StartHTTPSListener:input_type -> clientpb.HTTPListenerReq
	12,  // 23: rpcpb.PhantomRPC.StartHTTPListener:input_type -> clientpb.HTTPListenerReq
	0,   // 24: rpcpb.PhantomRPC.GetBeacons:input_type -> commonpb.Empty
	13,  // 25: rpcpb.PhantomRPC.GetBeacon:input_type -> clientpb.Beacon
	13,  // 26: rpcpb.PhantomRPC.RmBeacon:input_type -> clientpb.Beacon
	13,  // 27: rpcpb.PhantomRPC.GetBeaconTasks:input_type -> clientpb.Beacon
	14,  // 28: rpcpb.PhantomRPC.GetBeaconTaskContent:input_type -> clientpb.BeaconTask
	14,  // 29: rpcpb.PhantomRPC.CancelBeaconTask:input_type -> clientpb.BeaconTask
	15,  // 30: rpcpb.PhantomRPC.UpdateBeaconIntegrityInformation:input_type -> clientpb.BeaconIntegrity
	0,   // 31: rpcpb.PhantomRPC.GetJobs:input_type -> commonpb.Empty
	16,  // 32: rpcpb.PhantomRPC.KillJob:input_type -> clientpb.KillJobReq
	17,  // 33: rpcpb.PhantomRPC.RestartJobs:input_type -> clientpb.RestartJobReq
	18,  // 34: rpcpb.PhantomRPC.StartTCPStagerListener:input_type -> clientpb.StagerListenerReq
	19,  // 35: rpcpb.PhantomRPC.LootAdd:input_type -> clientpb.Loot
	19,  // 36: rpcpb.PhantomRPC.LootRm:input_type -> clientpb.Loot
	19,  // 37: rpcpb.PhantomRPC.LootUpdate:input_type -> clientpb.Loot
	19,  // 38: rpcpb.PhantomRPC.LootContent:input_type -> clientpb.Loot
	0,   // 39: rpcpb.PhantomRPC.LootAll:input_type -> commonpb.Empty
	0,   // 40: rpcpb.PhantomRPC.Creds:input_type -> commonpb.Empty
	20,  // 41: rpcpb.PhantomRPC.CredsAdd:input_type -> clientpb.Credentials
	20,  // 42: rpcpb.PhantomRPC.CredsRm:input_type -> clientpb.Credentials
	20,  // 43: rpcpb.PhantomRPC.CredsUpdate:input_type -> clientpb.Credentials
	21,  // 44: rpcpb.PhantomRPC.GetCredByID:input_type -> clientpb.Credential
	21,  // 45: rpcpb.PhantomRPC.GetCredsByHashType:input_type -> clientpb.Credential
	21,  // 46: rpcpb.PhantomRPC.GetPlaintextCredsByHashType:input_type -> clientpb.Credential
	21,  // 47: rpcpb.PhantomRPC.CredsSniffHashType:input_type -> clientpb.Credential
	0,   // 48: rpcpb.PhantomRPC.Hosts:input_type -> commonpb.Empty
	22,  // 49: rpcpb.PhantomRPC.Host:input_type -> clientpb.Host
	22,  // 50: rpcpb.PhantomRPC.HostRm:input_type -> clientpb.Host
	23,  // 51: rpcpb.PhantomRPC.HostIOCRm:input_type -> clientpb.IOC
	24,  // 52: rpcpb.PhantomRPC.Generate:input_type -> clientpb.GenerateReq
	25,  // 53: rpcpb.PhantomRPC.GenerateSpoofMetadata:input_type -> clientpb.GenerateSpoofMetadataReq
	26,  // 54: rpcpb.PhantomRPC.GenerateExternal:input_type -> clientpb.ExternalGenerateReq
	27,  // 55: rpcpb.PhantomRPC.GenerateExternalSaveBuild:input_type -> clientpb.ExternalImplantBinary
	28,  // 56: rpcpb.PhantomRPC.GenerateExternalGetBuildConfig:input_type -> clientpb.ImplantBuild
	29,  // 57: rpcpb.PhantomRPC.GenerateStage:input_type -> clientpb.GenerateStageReq
	30,  // 58: rpcpb.PhantomRPC.StageImplantBuild:input_type -> clientpb.ImplantStageReq
	0,   // 59: rpcpb.PhantomRPC.GetHTTPC2Profiles:input_type -> commonpb.Empty
	31,  // 60: rpcpb.PhantomRPC.GetHTTPC2ProfileByName:input_type -> clientpb.C2ProfileReq
	32,  // 61: rpcpb.PhantomRPC.SaveHTTPC2Profile:input_type -> clientpb.HTTPC2ConfigReq
	33,  // 62: rpcpb.PhantomRPC.BuilderRegister:input_type -> clientpb.Builder
	34,  // 63: rpcpb.PhantomRPC.BuilderTrigger:input_type -> clientpb.Event
	0,   // 64: rpcpb.PhantomRPC.Builders:input_type -> commonpb.Empty
	35,  // 65: rpcpb.PhantomRPC.GetCertificateInfo:input_type -> clientpb.CertificatesReq
	0,   // 66: rpcpb.PhantomRPC.GetCertificateAuthorityInfo:input_type -> commonpb.Empty
	36,  // 67: rpcpb.PhantomRPC.Crack:input_type -> clientpb.CrackCommand
	37,  // 68: rpcpb.PhantomRPC.CrackstationRegister:input_type -> clientpb.Crackstation
	34,  // 69: rpcpb.PhantomRPC.CrackstationTrigger:input_type -> clientpb.Event
	38,  // 70: rpcpb.PhantomRPC.CrackstationBenchmark:input_type -> clientpb.CrackBenchmark
	0,   // 71: rpcpb.PhantomRPC.Crackstations:input_type -> commonpb.Empty
	39,  // 72: rpcpb.PhantomRPC.CrackTaskByID:input_type -> clientpb.CrackTask
	39,  // 73: rpcpb.PhantomRPC.CrackTaskUpdate:input_type -> clientpb.CrackTask
	40,  // 74: rpcpb.PhantomRPC.CrackFilesList:input_type -> clientpb.CrackFile
	40,  // 75: rpcpb.PhantomRPC.CrackFileCreate:input_type -> clientpb.CrackFile
	41,  // 76: rpcpb.PhantomRPC.CrackFileChunkUpload:input_type -> clientpb.CrackFileChunk
	41,  // 77: rpcpb.PhantomRPC.CrackFileChunkDownload:input_type -> clientpb.CrackFileChunk
	40,  // 78: rpcpb.PhantomRPC.CrackFileComplete:input_type -> clientpb.CrackFile
	40,  // 79: rpcpb.PhantomRPC.CrackFileDelete:input_type -> clientpb.CrackFile
	42,  // 80: rpcpb.PhantomRPC.Regenerate:input_type -> clientpb.RegenerateReq
	0,   // 81: rpcpb.PhantomRPC.ImplantBuilds:input_type -> commonpb.Empty
	43,  // 82: rpcpb.PhantomRPC.DeleteImplantBuild:input_type -> clientpb.DeleteReq
	0,   // 83: rpcpb.PhantomRPC.Canaries:input_type -> commonpb.Empty
	0,   // 84: rpcpb.PhantomRPC.GenerateWGClientConfig:input_type -> commonpb.Empty
	0,   // 85: rpcpb.PhantomRPC.GenerateUniqueIP:input_type -> commonpb.Empty
	0,   // 86: rpcpb.PhantomRPC.ImplantProfiles:input_type -> commonpb.Empty
	43,  // 87: rpcpb.PhantomRPC.DeleteImplantProfile:input_type -> clientpb.DeleteReq
	44,  // 88: rpcpb.PhantomRPC.SaveImplantProfile:input_type -> clientpb.ImplantProfile
	45,  // 89: rpcpb.PhantomRPC.ShellcodeRDI:input_type -> clientpb.ShellcodeRDIReq
	0,   // 90: rpcpb.PhantomRPC.GetCompiler:input_type -> commonpb.Empty
	46,  // 91: rpcpb.PhantomRPC.ShellcodeEncoder:input_type -> clientpb.ShellcodeEncodeReq
	0,   // 92: rpcpb.PhantomRPC.ShellcodeEncoderMap:input_type -> commonpb.Empty
	0,   // 93: rpcpb.PhantomRPC.TrafficEncoderMap:input_type -> commonpb.Empty
	47,  // 94: rpcpb.PhantomRPC.TrafficEncoderAdd:input_type -> clientpb.TrafficEncoder
	47,  // 95: rpcpb.PhantomRPC.TrafficEncoderRm:input_type -> clientpb.TrafficEncoder
	0,   // 96: rpcpb.PhantomRPC.Websites:input_type -> commonpb.Empty
	48,  // 97: rpcpb.PhantomRPC.Website:input_type -> clientpb.Website
	48,  // 98: rpcpb.PhantomRPC.WebsiteRemove:input_type -> clientpb.Website
	49,  // 99: rpcpb.PhantomRPC.WebsiteAddContent:input_type -> clientpb.WebsiteAddContent
	49,  // 100: rpcpb.PhantomRPC.WebsiteUpdateContent:input_type -> clientpb.WebsiteAddContent
	50,  // 101: rpcpb.PhantomRPC.WebsiteRemoveContent:input_type -> clientpb.WebsiteRemoveContent
	51,  // 102: rpcpb.PhantomRPC.Ping:input_type -> phantompb.Ping
	52,  // 103: rpcpb.PhantomRPC.Ps:input_type -> phantompb.PsReq
	53,  // 104: rpcpb.PhantomRPC.Terminate:input_type -> phantompb.TerminateReq
	54,  // 105: rpcpb.PhantomRPC.Ifconfig:input_type -> phantompb.IfconfigReq
	55,  // 106: rpcpb.PhantomRPC.Netstat:input_type -> phantompb.NetstatReq
	56,  // 107: rpcpb.PhantomRPC.Ls:input_type -> phantompb.LsReq
	57,  // 108: rpcpb.PhantomRPC.Cd:input_type -> phantompb.CdReq
	58,  // 109: rpcpb.PhantomRPC.Pwd:input_type -> phantompb.PwdReq
	59,  // 110: rpcpb.PhantomRPC.Mv:input_type -> phantompb.MvReq
	60,  // 111: rpcpb.PhantomRPC.Cp:input_type -> phantompb.CpReq
	61,  // 112: rpcpb.PhantomRPC.Rm:input_type -> phantompb.RmReq
	62,  // 113: rpcpb.PhantomRPC.Mkdir:input_type -> phantompb.MkdirReq
	63,  // 114: rpcpb.PhantomRPC.Download:input_type -> phantompb.DownloadReq
	64,  // 115: rpcpb.PhantomRPC.Upload:input_type -> phantompb.UploadReq
	65,  // 116: rpcpb.PhantomRPC.Grep:input_type -> phantompb.GrepReq
	66,  // 117: rpcpb.PhantomRPC.Chmod:input_type -> phantompb.ChmodReq
	67,  // 118: rpcpb.PhantomRPC.Chown:input_type -> phantompb.ChownReq
	68,  // 119: rpcpb.PhantomRPC.Chtimes:input_type -> phantompb.ChtimesReq
	69,  // 120: rpcpb.PhantomRPC.MemfilesList:input_type -> phantompb.MemfilesListReq
	70,  // 121: rpcpb.PhantomRPC.MemfilesAdd:input_type -> phantompb.MemfilesAddReq
	71,  // 122: rpcpb.PhantomRPC.MemfilesRm:input_type -> phantompb.MemfilesRmReq
	72,  // 123: rpcpb.PhantomRPC.Mount:input_type -> phantompb.MountReq
	73,  // 124: rpcpb.PhantomRPC.ProcessDump:input_type -> phantompb.ProcessDumpReq
	74,  // 125: rpcpb.PhantomRPC.RunAs:input_type -> phantompb.RunAsReq
	75,  // 126: rpcpb.PhantomRPC.Impersonate:input_type -> phantompb.ImpersonateReq
	76,  // 127: rpcpb.PhantomRPC.RevToSelf:input_type -> phantompb.RevToSelfReq
	77,  // 128: rpcpb.PhantomRPC.GetSystem:input_type -> clientpb.GetSystemReq
	78,  // 129: rpcpb.PhantomRPC.Task:input_type -> phantompb.TaskReq
	79,  // 130: rpcpb.PhantomRPC.Msf:input_type -> clientpb.MSFReq
	80,  // 131: rpcpb.PhantomRPC.MsfRemote:input_type -> clientpb.MSFRemoteReq
	81,  // 132: rpcpb.PhantomRPC.ExecuteAssembly:input_type -> phantompb.ExecuteAssemblyReq
	82,  // 133: rpcpb.PhantomRPC.Migrate:input_type -> clientpb.MigrateReq
	83,  // 134: rpcpb.PhantomRPC.Execute:input_type -> phantompb.ExecuteReq
	84,  // 135: rpcpb.PhantomRPC.ExecuteWindows:input_type -> phantompb.ExecuteWindowsReq
	85,  // 136: rpcpb.PhantomRPC.ExecuteChildren:input_type -> phantompb.ExecuteChildrenReq
	86,  // 137: rpcpb.PhantomRPC.Sideload:input_type -> phantompb.SideloadReq
	87,  // 138: rpcpb.PhantomRPC.SpawnDll:input_type -> phantompb.InvokeSpawnDllReq
	88,  // 139: rpcpb.PhantomRPC.Screenshot:input_type -> phantompb.ScreenshotReq
	89,  // 140: rpcpb.PhantomRPC.CurrentTokenOwner:input_type -> phantompb.CurrentTokenOwnerReq
	90,  // 141: rpcpb.PhantomRPC.Services:input_type -> phantompb.ServicesReq
	91,  // 142: rpcpb.PhantomRPC.ServiceDetail:input_type -> phantompb.ServiceDetailReq
	92,  // 143: rpcpb.PhantomRPC.StartServiceByName:input_type -> phantompb.StartServiceByNameReq
	93,  // 144: rpcpb.PhantomRPC.PivotStartListener:input_type -> phantompb.PivotStartListenerReq
	94,  // 145: rpcpb.PhantomRPC.PivotStopListener:input_type -> phantompb.PivotStopListenerReq
	95,  // 146: rpcpb.PhantomRPC.PivotSessionListeners:input_type -> phantompb.PivotListenersReq
	0,   // 147: rpcpb.PhantomRPC.PivotGraph:input_type -> commonpb.Empty
	96,  // 148: rpcpb.PhantomRPC.StartService:input_type -> phantompb.StartServiceReq
	97,  // 149: rpcpb.PhantomRPC.StopService:input_type -> phantompb.StopServiceReq
	98,  // 150: rpcpb.PhantomRPC.RemoveService:input_type -> phantompb.RemoveServiceReq
	99,  // 151: rpcpb.PhantomRPC.MakeToken:input_type -> phantompb.MakeTokenReq
	100, // 152: rpcpb.PhantomRPC.GetEnv:input_type -> phantompb.EnvReq
	101, // 153: rpcpb.PhantomRPC.SetEnv:input_type -> phantompb.SetEnvReq
	102, // 154: rpcpb.PhantomRPC.UnsetEnv:input_type -> phantompb.UnsetEnvReq
	103, // 155: rpcpb.PhantomRPC.Backdoor:input_type -> clientpb.BackdoorReq
	104, // 156: rpcpb.PhantomRPC.RegistryRead:input_type -> phantompb.RegistryReadReq
	105, // 157: rpcpb.PhantomRPC.RegistryWrite:input_type -> phantompb.RegistryWriteReq
	106, // 158: rpcpb.PhantomRPC.RegistryCreateKey:input_type -> phantompb.RegistryCreateKeyReq
	107, // 159: rpcpb.PhantomRPC.RegistryDeleteKey:input_type -> phantompb.RegistryDeleteKeyReq
	108, // 160: rpcpb.PhantomRPC.RegistryListSubKeys:input_type -> phantompb.RegistrySubKeyListReq
	109, // 161: rpcpb.PhantomRPC.RegistryListValues:input_type -> phantompb.RegistryListValuesReq
	110, // 162: rpcpb.PhantomRPC.RegistryReadHive:input_type -> phantompb.RegistryReadHiveReq
	111, // 163: rpcpb.PhantomRPC.RunSSHCommand:input_type -> phantompb.SSHCommandReq
	112, // 164: rpcpb.PhantomRPC.HijackDLL:input_type -> clientpb.DllHijackReq
	113, // 165: rpcpb.PhantomRPC.GetPrivs:input_type -> phantompb.GetPrivsReq
	114, // 166: rpcpb.PhantomRPC.StartRportFwdListener:input_type -> phantompb.RportFwdStartListenerReq
	115, // 167: rpcpb.PhantomRPC.GetRportFwdListeners:input_type -> phantompb.RportFwdListenersReq
	116, // 168: rpcpb.PhantomRPC.StopRportFwdListener:input_type -> phantompb.RportFwdStopListenerReq
	117, // 169: rpcpb.PhantomRPC.OpenSession:input_type -> phantompb.OpenSession
	118, // 170: rpcpb.PhantomRPC.CloseSession:input_type -> phantompb.CloseSession
	119, // 171: rpcpb.PhantomRPC.RegisterExtension:input_type -> phantompb.RegisterExtensionReq
	120, // 172: rpcpb.PhantomRPC.CallExtension:input_type -> phantompb.CallExtensionReq
	121, // 173: rpcpb.PhantomRPC.ListExtensions:input_type -> phantompb.ListExtensionsReq
	122, // 174: rpcpb.PhantomRPC.RegisterWasmExtension:input_type -> phantompb.RegisterWasmExtensionReq
	123, // 175: rpcpb.PhantomRPC.ListWasmExtensions:input_type -> phantompb.ListWasmExtensionsReq
	124, // 176: rpcpb.PhantomRPC.ExecWasmExtension:input_type -> phantompb.ExecWasmExtensionReq
	125, // 177: rpcpb.PhantomRPC.WGStartPortForward:input_type -> phantompb.WGPortForwardStartReq
	126, // 178: rpcpb.PhantomRPC.WGStopPortForward:input_type -> phantompb.WGPortForwardStopReq
	127, // 179: rpcpb.PhantomRPC.WGStartSocks:input_type -> phantompb.WGSocksStartReq
	128, // 180: rpcpb.PhantomRPC.WGStopSocks:input_type -> phantompb.WGSocksStopReq
	129, // 181: rpcpb.PhantomRPC.WGListForwarders:input_type -> phantompb.WGTCPForwardersReq
	130, // 182: rpcpb.PhantomRPC.WGListSocksServers:input_type -> phantompb.WGSocksServersReq
	131, // 183: rpcpb.PhantomRPC.Shell:input_type -> phantompb.ShellReq
	132, // 184: rpcpb.PhantomRPC.ShellResize:input_type -> phantompb.ShellResizeReq
	133, // 185: rpcpb.PhantomRPC.Portfwd:input_type -> phantompb.PortfwdReq
	134, // 186: rpcpb.PhantomRPC.CreateSocks:input_type -> phantompb.Socks
	134, // 187: rpcpb.PhantomRPC.CloseSocks:input_type -> phantompb.Socks
	135, // 188: rpcpb.PhantomRPC.SocksProxy:input_type -> phantompb.SocksData
	136, // 189: rpcpb.PhantomRPC.CreateTunnel:input_type -> phantompb.Tunnel
	136, // 190: rpcpb.PhantomRPC.CloseTunnel:input_type -> phantompb.Tunnel
	137, // 191: rpcpb.PhantomRPC.TunnelData:input_type -> phantompb.TunnelData
	0,   // 192: rpcpb.PhantomRPC.Events:input_type -> commonpb.Empty
	138, // 193: rpcpb.PhantomRPC.GetAuditLogs:input_type -> clientpb.AuditLogFilter
	139, // 194: rpcpb.PhantomRPC.CreateEngagement:input_type -> clientpb.Engagement
	0,   // 195: rpcpb.PhantomRPC.GetEngagements:input_type -> commonpb.Empty
	140, // 196: rpcpb.PhantomRPC.GetEngagement:input_type -> clientpb.EngagementReq
	139, // 197: rpcpb.PhantomRPC.UpdateEngagement:input_type -> clientpb.Engagement
	140, // 198: rpcpb.PhantomRPC.DeleteEngagement:input_type -> clientpb.EngagementReq
	141, // 199: rpcpb.PhantomRPC.AssignSessionToEngagement:input_type -> clientpb.AssignTargetReq
	141, // 200: rpcpb.PhantomRPC.AssignBeaconToEngagement:input_type -> clientpb.AssignTargetReq
	141, // 201: rpcpb.PhantomRPC.RemoveSessionFromEngagement:input_type -> clientpb.AssignTargetReq
	141, // 202: rpcpb.PhantomRPC.RemoveBeaconFromEngagement:input_type -> clientpb.AssignTargetReq
	142, // 203: rpcpb.PhantomRPC.AddFinding:input_type -> clientpb.Finding
	142, // 204: rpcpb.PhantomRPC.UpdateFinding:input_type -> clientpb.Finding
	142, // 205: rpcpb.PhantomRPC.DeleteFinding:input_type -> clientpb.Finding
	143, // 206: rpcpb.PhantomRPC.GetVersion:output_type -> clientpb.Version
	0,   // 207: rpcpb.PhantomRPC.ClientLog:output_type -> commonpb.Empty
	144, // 208: rpcpb.PhantomRPC.GetOperators:output_type -> clientpb.Operators
	0,   // 209: rpcpb.PhantomRPC.Kill:output_type -> commonpb.Empty
	145, // 210: rpcpb.PhantomRPC.Reconfigure:output_type -> phantompb.Reconfigure
	0,   // 211: rpcpb.PhantomRPC.Rename:output_type -> commonpb.Empty
	146, // 212: rpcpb.PhantomRPC.GetSessions:output_type -> clientpb.Sessions
	147, // 213: rpcpb.PhantomRPC.MonitorStart:output_type -> commonpb.Response
	0,   // 214: rpcpb.PhantomRPC.MonitorStop:output_type -> commonpb.Empty
	148, // 215: rpcpb.PhantomRPC.MonitorListConfig:output_type -> clientpb.MonitoringProviders
	147, // 216: rpcpb.PhantomRPC.MonitorAddConfig:output_type -> commonpb.Response
	147, // 217: rpcpb.PhantomRPC.MonitorDelConfig:output_type -> commonpb.Response
	149, // 218: rpcpb.PhantomRPC.GetAIProviders:output_type -> clientpb.AIProviderConfigs
	150, // 219: rpcpb.PhantomRPC.GetAIConversations:output_type -> clientpb.AIConversations
	7,   // 220: rpcpb.PhantomRPC.GetAIConversation:output_type -> clientpb.AIConversation
	7,   // 221: rpcpb.PhantomRPC.SaveAIConversation:output_type -> clientpb.AIConversation
	0,   // 222: rpcpb.PhantomRPC.DeleteAIConversation:output_type -> commonpb.Empty
	151, // 223: rpcpb.PhantomRPC.GetAIConversationMessages:output_type -> clientpb.AIConversationMessages
	8,   // 224: rpcpb.PhantomRPC.SaveAIConversationMessage:output_type -> clientpb.AIConversationMessage
	152, // 225: rpcpb.PhantomRPC.StartMTLSListener:output_type -> clientpb.ListenerJob
	152, // 226: rpcpb.PhantomRPC.StartWGListener:output_type -> clientpb.ListenerJob
	152, // 227: rpcpb.PhantomRPC.StartDNSListener:output_type -> clientpb.ListenerJob
	152, // 228: rpcpb.PhantomRPC.StartHTTPSListener:output_type -> clientpb.ListenerJob
	152, // 229: rpcpb.PhantomRPC.StartHTTPListener:output_type -> clientpb.ListenerJob
	153, // 230: rpcpb.PhantomRPC.GetBeacons:output_type -> clientpb.Beacons
	13,  // 231: rpcpb.PhantomRPC.GetBeacon:output_type -> clientpb.Beacon
	0,   // 232: rpcpb.PhantomRPC.RmBeacon:output_type -> commonpb.Empty
	154, // 233: rpcpb.PhantomRPC.GetBeaconTasks:output_type -> clientpb.BeaconTasks
	14,  // 234: rpcpb.PhantomRPC.GetBeaconTaskContent:output_type -> clientpb.BeaconTask
	14,  // 235: rpcpb.PhantomRPC.CancelBeaconTask:output_type -> clientpb.BeaconTask
	0,   // 236: rpcpb.PhantomRPC.UpdateBeaconIntegrityInformation:output_type -> commonpb.Empty
	155, // 237: rpcpb.PhantomRPC.GetJobs:output_type -> clientpb.Jobs
	156, // 238: rpcpb.PhantomRPC.KillJob:output_type -> clientpb.KillJob
	0,   // 239: rpcpb.PhantomRPC.RestartJobs:output_type -> commonpb.Empty
	157, // 240: rpcpb.PhantomRPC.StartTCPStagerListener:output_type -> clientpb.StagerListener
	19,  // 241: rpcpb.PhantomRPC.LootAdd:output_type -> clientpb.Loot
	0,   // 242: rpcpb.PhantomRPC.LootRm:output_type -> commonpb.Empty
	19,  // 243: rpcpb.PhantomRPC.LootUpdate:output_type -> clientpb.Loot
	19,  // 244: rpcpb.PhantomRPC.LootContent:output_type -> clientpb.Loot
	158, // 245: rpcpb.PhantomRPC.LootAll:output_type -> clientpb.AllLoot
	20,  // 246: rpcpb.PhantomRPC.Creds:output_type -> clientpb.Credentials
	0,   // 247: rpcpb.PhantomRPC.CredsAdd:output_type -> commonpb.Empty
	0,   // 248: rpcpb.PhantomRPC.CredsRm:output_type -> commonpb.Empty
	0,   // 249: rpcpb.PhantomRPC.CredsUpdate:output_type -> commonpb.Empty
	21,  // 250: rpcpb.PhantomRPC.GetCredByID:output_type -> clientpb.Credential
	20,  // 251: rpcpb.PhantomRPC.GetCredsByHashType:output_type -> clientpb.Credentials
	20,  // 252: rpcpb.PhantomRPC.GetPlaintextCredsByHashType:output_type -> clientpb.Credentials
	21,  // 253: rpcpb.PhantomRPC.CredsSniffHashType:output_type -> clientpb.Credential
	159, // 254: rpcpb.PhantomRPC.Hosts:output_type -> clientpb.AllHosts
	22,  // 255: rpcpb.PhantomRPC.Host:output_type -> clientpb.Host
	0,   // 256: rpcpb.PhantomRPC.HostRm:output_type -> commonpb.Empty
	0,   // 257: rpcpb.PhantomRPC.HostIOCRm:output_type -> commonpb.Empty
	160, // 258: rpcpb.PhantomRPC.Generate:output_type -> clientpb.Generate
	0,   // 259: rpcpb.PhantomRPC.GenerateSpoofMetadata:output_type -> commonpb.Empty
	161, // 260: rpcpb.PhantomRPC.GenerateExternal:output_type -> clientpb.ExternalImplantConfig
	0,   // 261: rpcpb.PhantomRPC.GenerateExternalSaveBuild:output_type -> commonpb.Empty
	161, // 262: rpcpb.PhantomRPC.GenerateExternalGetBuildConfig:output_type -> clientpb.ExternalImplantConfig
	160, // 263: rpcpb.PhantomRPC.GenerateStage:output_type -> clientpb.Generate
	0,   // 264: rpcpb.PhantomRPC.StageImplantBuild:output_type -> commonpb.Empty
	162, // 265: rpcpb.PhantomRPC.GetHTTPC2Profiles:output_type -> clientpb.HTTPC2Configs
	163, // 266: rpcpb.PhantomRPC.GetHTTPC2ProfileByName:output_type -> clientpb.HTTPC2Config
	0,   // 267: rpcpb.PhantomRPC.SaveHTTPC2Profile:output_type -> commonpb.Empty
	34,  // 268: rpcpb.PhantomRPC.BuilderRegister:output_type -> clientpb.Event
	0,   // 269: rpcpb.PhantomRPC.BuilderTrigger:output_type -> commonpb.Empty
	164, // 270: rpcpb.PhantomRPC.Builders:output_type -> clientpb.Builders
	165, // 271: rpcpb.PhantomRPC.GetCertificateInfo:output_type -> clientpb.CertificateInfo
	166, // 272: rpcpb.PhantomRPC.GetCertificateAuthorityInfo:output_type -> clientpb.CertificateAuthorityInfo
	167, // 273: rpcpb.PhantomRPC.Crack:output_type -> clientpb.CrackResponse
	34,  // 274: rpcpb.PhantomRPC.CrackstationRegister:output_type -> clientpb.Event
	0,   // 275: rpcpb.PhantomRPC.CrackstationTrigger:output_type -> commonpb.Empty
	0,   // 276: rpcpb.PhantomRPC.CrackstationBenchmark:output_type -> commonpb.Empty
	168, // 277: rpcpb.PhantomRPC.Crackstations:output_type -> clientpb.Crackstations
	39,  // 278: rpcpb.PhantomRPC.CrackTaskByID:output_type -> clientpb.CrackTask
	0,   // 279: rpcpb.PhantomRPC.CrackTaskUpdate:output_type -> commonpb.Empty
	169, // 280: rpcpb.PhantomRPC.CrackFilesList:output_type -> clientpb.CrackFiles
	40,  // 281: rpcpb.PhantomRPC.CrackFileCreate:output_type -> clientpb.CrackFile
	0,   // 282: rpcpb.PhantomRPC.CrackFileChunkUpload:output_type -> commonpb.Empty
	41,  // 283: rpcpb.PhantomRPC.CrackFileChunkDownload:output_type -> clientpb.CrackFileChunk
	0,   // 284: rpcpb.PhantomRPC.CrackFileComplete:output_type -> commonpb.Empty
	0,   // 285: rpcpb.PhantomRPC.CrackFileDelete:output_type -> commonpb.Empty
	160, // 286: rpcpb.PhantomRPC.Regenerate:output_type -> clientpb.Generate
	170, // 287: rpcpb.PhantomRPC.ImplantBuilds:output_type -> clientpb.ImplantBuilds
	0,   // 288: rpcpb.PhantomRPC.DeleteImplantBuild:output_type -> commonpb.Empty
	171, // 289: rpcpb.PhantomRPC.Canaries:output_type -> clientpb.Canaries
	172, // 290: rpcpb.PhantomRPC.GenerateWGClientConfig:output_type -> clientpb.WGClientConfig
	173, // 291: rpcpb.PhantomRPC.GenerateUniqueIP:output_type -> clientpb.UniqueWGIP
	174, // 292: rpcpb.PhantomRPC.ImplantProfiles:output_type -> clientpb.ImplantProfiles
	0,   // 293: rpcpb.PhantomRPC.DeleteImplantProfile:output_type -> commonpb.Empty
	44,  // 294: rpcpb.PhantomRPC.SaveImplantProfile:output_type -> clientpb.ImplantProfile
	175, // 295: rpcpb.PhantomRPC.ShellcodeRDI:output_type -> clientpb.ShellcodeRDI
	176, // 296: rpcpb.PhantomRPC.GetCompiler:output_type -> clientpb.Compiler
	177, // 297: rpcpb.PhantomRPC.ShellcodeEncoder:output_type -> clientpb.ShellcodeEncode
	178, // 298: rpcpb.PhantomRPC.ShellcodeEncoderMap:output_type -> clientpb.ShellcodeEncoderMap
	179, // 299: rpcpb.PhantomRPC.TrafficEncoderMap:output_type -> clientpb.TrafficEncoderMap
	180, // 300: rpcpb.PhantomRPC.TrafficEncoderAdd:output_type -> clientpb.TrafficEncoderTests
	0,   // 301: rpcpb.PhantomRPC.TrafficEncoderRm:output_type -> commonpb.Empty
	181, // 302: rpcpb.PhantomRPC.Websites:output_type -> clientpb.Websites
	48,  // 303: rpcpb.PhantomRPC.Website:output_type -> clientpb.Website
	0,   // 304: rpcpb.PhantomRPC.WebsiteRemove:output_type -> commonpb.Empty
	48,  // 305: rpcpb.PhantomRPC.WebsiteAddContent:output_type -> clientpb.Website
	48,  // 306: rpcpb.PhantomRPC.WebsiteUpdateContent:output_type -> clientpb.Website
	48,  // 307: rpcpb.PhantomRPC.WebsiteRemoveContent:output_type -> clientpb.Website
	51,  // 308: rpcpb.PhantomRPC.Ping:output_type -> phantompb.Ping
	182, // 309: rpcpb.PhantomRPC.Ps:output_type -> phantompb.Ps
	183, // 310: rpcpb.PhantomRPC.Terminate:output_type -> phantompb.Terminate
	184, // 311: rpcpb.PhantomRPC.Ifconfig:output_type -> phantompb.Ifconfig
	185, // 312: rpcpb.PhantomRPC.Netstat:output_type -> phantompb.Netstat
	186, // 313: rpcpb.PhantomRPC.Ls:output_type -> phantompb.Ls
	187, // 314: rpcpb.PhantomRPC.Cd:output_type -> phantompb.Pwd
	187, // 315: rpcpb.PhantomRPC.Pwd:output_type -> phantompb.Pwd
	188, // 316: rpcpb.PhantomRPC.Mv:output_type -> phantompb.Mv
	189, // 317: rpcpb.PhantomRPC.Cp:output_type -> phantompb.Cp
	190, // 318: rpcpb.PhantomRPC.Rm:output_type -> phantompb.Rm
	191, // 319: rpcpb.PhantomRPC.Mkdir:output_type -> phantompb.Mkdir
	192, // 320: rpcpb.PhantomRPC.Download:output_type -> phantompb.Download
	193, // 321: rpcpb.PhantomRPC.Upload:output_type -> phantompb.Upload
	194, // 322: rpcpb.PhantomRPC.Grep:output_type -> phantompb.Grep
	195, // 323: rpcpb.PhantomRPC.Chmod:output_type -> phantompb.Chmod
	196, // 324: rpcpb.PhantomRPC.Chown:output_type -> phantompb.Chown
	197, // 325: rpcpb.PhantomRPC.Chtimes:output_type -> phantompb.Chtimes
	186, // 326: rpcpb.PhantomRPC.MemfilesList:output_type -> phantompb.Ls
	198, // 327: rpcpb.PhantomRPC.MemfilesAdd:output_type -> phantompb.MemfilesAdd
	199, // 328: rpcpb.PhantomRPC.MemfilesRm:output_type -> phantompb.MemfilesRm
	200, // 329: rpcpb.PhantomRPC.Mount:output_type -> phantompb.Mount
	201, // 330: rpcpb.PhantomRPC.ProcessDump:output_type -> phantompb.ProcessDump
	202, // 331: rpcpb.PhantomRPC.RunAs:output_type -> phantompb.RunAs
	203, // 332: rpcpb.PhantomRPC.Impersonate:output_type -> phantompb.Impersonate
	204, // 333: rpcpb.PhantomRPC.RevToSelf:output_type -> phantompb.RevToSelf
	205, // 334: rpcpb.PhantomRPC.GetSystem:output_type -> phantompb.GetSystem
	206, // 335: rpcpb.PhantomRPC.Task:output_type -> phantompb.Task
	206, // 336: rpcpb.PhantomRPC.Msf:output_type -> phantompb.Task
	206, // 337: rpcpb.PhantomRPC.MsfRemote:output_type -> phantompb.Task
	207, // 338: rpcpb.PhantomRPC.ExecuteAssembly:output_type -> phantompb.ExecuteAssembly
	208, // 339: rpcpb.PhantomRPC.Migrate:output_type -> phantompb.Migrate
	209, // 340: rpcpb.PhantomRPC.Execute:output_type -> phantompb.Execute
	209, // 341: rpcpb.PhantomRPC.ExecuteWindows:output_type -> phantompb.Execute
	210, // 342: rpcpb.PhantomRPC.ExecuteChildren:output_type -> phantompb.ExecuteChildren
	211, // 343: rpcpb.PhantomRPC.Sideload:output_type -> phantompb.Sideload
	212, // 344: rpcpb.PhantomRPC.SpawnDll:output_type -> phantompb.SpawnDll
	213, // 345: rpcpb.PhantomRPC.Screenshot:output_type -> phantompb.Screenshot
	214, // 346: rpcpb.PhantomRPC.CurrentTokenOwner:output_type -> phantompb.CurrentTokenOwner
	215, // 347: rpcpb.PhantomRPC.Services:output_type -> phantompb.Services
	216, // 348: rpcpb.PhantomRPC.ServiceDetail:output_type -> phantompb.ServiceDetail
	217, // 349: rpcpb.PhantomRPC.StartServiceByName:output_type -> phantompb.ServiceInfo
	218, // 350: rpcpb.PhantomRPC.PivotStartListener:output_type -> phantompb.PivotListener
	0,   // 351: rpcpb.PhantomRPC.PivotStopListener:output_type -> commonpb.Empty
	219, // 352: rpcpb.PhantomRPC.PivotSessionListeners:output_type -> phantompb.PivotListeners
	220, // 353: rpcpb.PhantomRPC.PivotGraph:output_type -> clientpb.PivotGraph
	217, // 354: rpcpb.PhantomRPC.StartService:output_type -> phantompb.ServiceInfo
	217, // 355: rpcpb.PhantomRPC.StopService:output_type -> phantompb.ServiceInfo
	217, // 356: rpcpb.PhantomRPC.RemoveService:output_type -> phantompb.ServiceInfo
	221, // 357: rpcpb.PhantomRPC.MakeToken:output_type -> phantompb.MakeToken
	222, // 358: rpcpb.PhantomRPC.GetEnv:output_type -> phantompb.EnvInfo
	223, // 359: rpcpb.PhantomRPC.SetEnv:output_type -> phantompb.SetEnv
	224, // 360: rpcpb.PhantomRPC.UnsetEnv:output_type -> phantompb.UnsetEnv
	225, // 361: rpcpb.PhantomRPC.Backdoor:output_type -> clientpb.Backdoor
	226, // 362: rpcpb.PhantomRPC.RegistryRead:output_type -> phantompb.RegistryRead
	227, // 363: rpcpb.PhantomRPC.RegistryWrite:output_type -> phantompb.RegistryWrite
	228, // 364: rpcpb.PhantomRPC.RegistryCreateKey:output_type -> phantompb.RegistryCreateKey
	229, // 365: rpcpb.PhantomRPC.RegistryDeleteKey:output_type -> phantompb.RegistryDeleteKey
	230, // 366: rpcpb.PhantomRPC.RegistryListSubKeys:output_type -> phantompb.RegistrySubKeyList
	231, // 367: rpcpb.PhantomRPC.RegistryListValues:output_type -> phantompb.RegistryValuesList
	232, // 368: rpcpb.PhantomRPC.RegistryReadHive:output_type -> phantompb.RegistryReadHive
	233, // 369: rpcpb.PhantomRPC.RunSSHCommand:output_type -> phantompb.SSHCommand
	234, // 370: rpcpb.PhantomRPC.HijackDLL:output_type -> clientpb.DllHijack
	235, // 371: rpcpb.PhantomRPC.GetPrivs:output_type -> phantompb.GetPrivs
	236, // 372: rpcpb.PhantomRPC.StartRportFwdListener:output_type -> phantompb.RportFwdListener
	237, // 373: rpcpb.PhantomRPC.GetRportFwdListeners:output_type -> phantompb.RportFwdListeners
	236, // 374: rpcpb.PhantomRPC.StopRportFwdListener:output_type -> phantompb.RportFwdListener
	117, // 375: rpcpb.PhantomRPC.OpenSession:output_type -> phantompb.OpenSession
	0,   // 376: rpcpb.PhantomRPC.CloseSession:output_type -> commonpb.Empty
	238, // 377: rpcpb.PhantomRPC.RegisterExtension:output_type -> phantompb.RegisterExtension
	239, // 378: rpcpb.PhantomRPC.CallExtension:output_type -> phantompb.CallExtension
	240, // 379: rpcpb.PhantomRPC.ListExtensions:output_type -> phantompb.ListExtensions
	241, // 380: rpcpb.PhantomRPC.RegisterWasmExtension:output_type -> phantompb.RegisterWasmExtension
	242, // 381: rpcpb.PhantomRPC.ListWasmExtensions:output_type -> phantompb.ListWasmExtensions
	243, // 382: rpcpb.PhantomRPC.ExecWasmExtension:output_type -> phantompb.ExecWasmExtension
	244, // 383: rpcpb.PhantomRPC.WGStartPortForward:output_type -> phantompb.WGPortForward
	244, // 384: rpcpb.PhantomRPC.WGStopPortForward:output_type -> phantompb.WGPortForward
	245, // 385: rpcpb.PhantomRPC.WGStartSocks:output_type -> phantompb.WGSocks
	245, // 386: rpcpb.PhantomRPC.WGStopSocks:output_type -> phantompb.WGSocks
	246, // 387: rpcpb.PhantomRPC.WGListForwarders:output_type -> phantompb.WGTCPForwarders
	247, // 388: rpcpb.PhantomRPC.WGListSocksServers:output_type -> phantompb.WGSocksServers
	248, // 389: rpcpb.PhantomRPC.Shell:output_type -> phantompb.Shell
	0,   // 390: rpcpb.PhantomRPC.ShellResize:output_type -> commonpb.Empty
	249, // 391: rpcpb.PhantomRPC.Portfwd:output_type -> phantompb.Portfwd
	134, // 392: rpcpb.PhantomRPC.CreateSocks:output_type -> phantompb.Socks
	0,   // 393: rpcpb.PhantomRPC.CloseSocks:output_type -> commonpb.Empty
	135, // 394: rpcpb.PhantomRPC.SocksProxy:output_type -> phantompb.SocksData
	136, // 395: rpcpb.PhantomRPC.CreateTunnel:output_type -> phantompb.Tunnel
	0,   // 396: rpcpb.PhantomRPC.CloseTunnel:output_type -> commonpb.Empty
	137, // 397: rpcpb.PhantomRPC.TunnelData:output_type -> phantompb.TunnelData
	34,  // 398: rpcpb.PhantomRPC.Events:output_type -> clientpb.Event
	250, // 399: rpcpb.PhantomRPC.GetAuditLogs:output_type -> clientpb.AuditLogs
	139, // 400: rpcpb.PhantomRPC.CreateEngagement:output_type -> clientpb.Engagement
	251, // 401: rpcpb.PhantomRPC.GetEngagements:output_type -> clientpb.Engagements
	139, // 402: rpcpb.PhantomRPC.GetEngagement:output_type -> clientpb.Engagement
	139, // 403: rpcpb.PhantomRPC.UpdateEngagement:output_type -> clientpb.Engagement
	0,   // 404: rpcpb.PhantomRPC.DeleteEngagement:output_type -> commonpb.Empty
	0,   // 405: rpcpb.PhantomRPC.AssignSessionToEngagement:output_type -> commonpb.Empty
	0,   // 406: rpcpb.PhantomRPC.AssignBeaconToEngagement:output_type -> commonpb.Empty
	0,   // 407: rpcpb.PhantomRPC.RemoveSessionFromEngagement:output_type -> commonpb.Empty
	0,   // 408: rpcpb.PhantomRPC.RemoveBeaconFromEngagement:output_type -> commonpb.Empty
	142, // 409: rpcpb.PhantomRPC.AddFinding:output_type -> clientpb.Finding
	142, // 410: rpcpb.PhantomRPC.UpdateFinding:output_type -> clientpb.Finding
	0,   // 411: rpcpb.PhantomRPC.DeleteFinding:output_type -> commonpb.Empty
	206, // [206:412] is the sub-list for method output_type
	0,   // [0:206] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_rpcpb_services_proto_init() }
func file_rpcpb_services_proto_init() {
	if File_rpcpb_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcpb_services_proto_rawDesc), len(file_rpcpb_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcpb_services_proto_goTypes,
		DependencyIndexes: file_rpcpb_services_proto_depIdxs,
	}.Build()
	File_rpcpb_services_proto = out.File
	file_rpcpb_services_proto_goTypes = nil
	file_rpcpb_services_proto_depIdxs = nil
}
